# Generated by Django 5.1 on 2024-08-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
